Dec.1 API Halfway Done
johnnysong-cc/COMP309Proj2 pull request #5
Opened 2023-12-01 06:42 UTC by johnnysong-cc

- All the backend logic except a classification model have been done but not tested yet.
  - `describe_data()`
  - `explorative_assessment()`
  - `correlation_assessment()`
  - `chi2_assessment()`
  - `data_cleansing_general()`
  - `impute_missing_values()`
  - `normalize_data()`
  - `label_encoding()`
  - `explorative_vis()`
- A linear regression model is done but not very useful due to low scores. The dataset doesn't seem to fit the model.
- A logistic regression model is done with nice looking scores and metrics.
- Data cleansing and categorical labeling logic can be further refined.
- More visualization can be created based on needs.
- Previously written scripts are stored in `~/logic_scripts/`. They are heavily documented and can be helpful to documentation tasks.

2023-12-01 18:19 UTC, jque4 approved these changes

2023-12-04 19:50 UTC, ThedysonLuzon approved these changes

2023-12-05 23:02 UTC, jque4 requested changes
@glad2os had issues running the code. The main error reported is: `AttributeError: module 'numpy' has no attribute 'DataFrame'`

I was able to run the code, however, I needed to replace all references to `np.DataFrame` with `pd.DataFrame`. 

I would recommend using pandas DataFrames instead if possible. If you still need to use NumPy DataFrames, you may convert them using the method outlined [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html).

2023-12-06 04:07 UTC, johnnysong-cc commented
Thanks for @jque4 and @glad2os to point out the `np.DataFrame` issue which was a serious typo. This PR will be withdrawn.

2023-12-06 04:12 UTC, closed without merging